[package]
authors = ["Fabien Bellanger <valentil@gmail.com>"]
description = "ESC/POS printer driver"
documentation = "https://docs.rs/escpos"
edition = "2021"
homepage = "https://github.com/fabienbellanger/escpos-rs"
keywords = ["esc", "printer", "driver", "pos", "usb"]
license = "MIT"
name = "escpos"
readme = "README.md"
repository = "https://github.com/fabienbellanger/escpos-rs"
version = "0.12.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
barcodes = []
codes_2d = []
graphics = ["dep:image"]
hidapi = ["dep:hidapi"]
serial_port = ["dep:serialport"]
usb = ["dep:rusb"]
native_usb = ["dep:nusb", "dep:futures-lite"]
default = ["barcodes", "codes_2d"]
full = [
    "barcodes",
    "codes_2d",
    "graphics",
    "usb",
    "native_usb",
    "hidapi",
    "serial_port",
]

[dependencies]
encoding_rs = "0.8.34"
futures-lite = { version = "2.3.0", optional = true }
hidapi = { version = "2.6.1", optional = true }
image = { version = "0.25.1", optional = true }
lazy_static = "1.4.0"
log = "0.4.21"
nusb = { version = "0.1.8", optional = true }
rusb = { version = "0.9.3", optional = true }
serde = { version = "1.0.203", features = ["derive"] }
serialport = { version = "4.3.0", optional = true }

[dev-dependencies]
env_logger = "0.11.3"

[package.metadata.docs.rs]
all-features = true
